/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ChatInput: typeof import('./src/components/ChatInput.vue')['default']
    DocumentList: typeof import('./src/components/KbDetails/kbDocument/DocumentList.vue')['default']
    Documents: typeof import('./src/components/KbDetails/documents.vue')['default']
    DocumentUpload: typeof import('./src/components/KbDetails/kbDocument/DocumentUpload.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElCon: typeof import('element-plus/es')['ElCon']
    ElConfig: typeof import('element-plus/es')['ElConfig']
    ElConfigP: typeof import('element-plus/es')['ElConfigP']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    ElDescriptions: typeof import('element-plus/es')['ElDescriptions']
    ElDescriptionsItem: typeof import('element-plus/es')['ElDescriptionsItem']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElPopconfirm: typeof import('element-plus/es')['ElPopconfirm']
    ElProgress: typeof import('element-plus/es')['ElProgress']
    ElSpinner: typeof import('element-plus/es')['ElSpinner']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElUpload: typeof import('element-plus/es')['ElUpload']
    KDdocuments: typeof import('./src/components/KbDetails/KDdocuments.vue')['default']
    KDretrieval: typeof import('./src/components/KbDetails/KDretrieval.vue')['default']
    KDretrival: typeof import('./src/components/KbDetails/KDretrival.vue')['default']
    KDsetting: typeof import('./src/components/KbDetails/KDsetting.vue')['default']
    MessageBubble: typeof import('./src/components/MessageBubble.vue')['default']
    Nav: typeof import('./src/components/nav.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
